### ISSUE TITLE
迁移学习部分的一些问题

### ISSUE THREAD

**Issue by Meredith-z** [BrunoQin/ENSO-ASC#1]
秦博士您好，由于没有找到个人联系方式，就在这里留言了。我精读了您的这篇论文，想请教一下您transfer learning部分的fine-tune层是怎么设置的？具体是哪些层冻结，哪些层做微调，可以详说一下吗？谢谢！

**Comment by BrunoQin** [comment]
您好，这篇论文使用了两个数据集对模型进行训练。其中NOAA提供的再分析资料时间跨度较长，即数据量比较充分，我们先使用这个数据集进行训练；RSS提供的遥感资料时间跨度较短，但是精度（分辨率）较高（且咨询了气象方面的专家，认为这个数据可以当做标签数据），我们就将使用再分析资料训练好的模型，在遥感训练集上继续训练。关于您提到问题我拓展回答一下：
1. 再分析资料和遥感资料分辨率不匹配：我们将再分析资料插值，提升8倍分辨率（2->0.25）。这样统一使用一个模型就可以在两个数据集上进行训练，而不需要额外的卷积层（或其他层）来调整模型输入尺寸；
2. 模型冻结问题：由于已经进行了分辨率调整，且两个数据集的特征不同，（其实数据分布有可能不太一样，且除了SST，其他物理变量的含义均略有不同），我们认为冻结某些层进行训练是不合适的。我们纯粹是把在再分析资料的训练当做给模型提供了一个更好的初始化，且克服了遥感图像资料过少的问题。总之就是在使用再分析资料训练收敛后，直接利用遥感资料继续训练。模型没有冻结。
3. 关于冻结是否有效的讨论：如果两个数据集的分辨率不一致，又不想利用插值来破坏原数据特征（毕竟插值可能会造成数据平滑，缺少物理细节），那么可以在利用高分辨率数据集进行训练前，多加几层卷积来调整分辨率（即feature map的shape），而剩余模型部分可以利用训练好的参数。至于模型是否需要冻结，要看迁移学习不同数据集的来源是否一致，特点是否一致，甚至数据采集方法是否一致，否则可认为是不同的预测任务（个人观点），那么模型无需冻结。（此时可将迁移学习视作提供了优秀的模型初始化）

您的问题非常有价值，非常感谢！不知道我是否解决了您的疑惑。本git库我们还会继续完善，包括详细的运行脚本与预测脚本。如果任何问题（包括环境配置与运行等）均可与我随时联系！

**Comment by Meredith-z** [comment]
非常感谢您的回复！根据您的介绍，我的理解就是：使用再分析数据进行训练，保存模型权重，作为遥感数据训练时的初始化权重，然后再做训练。ps，您的代码结构和逻辑都写的非常清晰，向您学习😀

**Comment by BrunoQin** [comment]
对的，如果数据充足其实不必迁移训练。但是ENSO是一个年循环时间，研究者关注月平均变化，因此从有观测以来月平均数据还是比较少的，尤其是这篇文章利用了多物理量，优质的观测数据更是少。

另外也可利用CMIP计划提供的模式模拟数据预训练模型，而后进行迁移训练。模式模拟资料本身蕴含丰富动力特征与先验物理知识，分辨率和时间跨度更是可调的，是非常好的气象资料。
